### PR TITLE
chore(package): update to liftoff@3

### PR DESCRIPTION
**Pull request by saschanaz**
Solves:

```
  High            Regular Expression Denial of Service

  Package         minimatch

  Dependency of   liftoff

  Path            liftoff > findup-sync > glob > minimatch

  More info       https://npmjs.com/advisories/118
```

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Heh, we should probably update the .travis.yml ... check the node version 😂

**Comment by marcoscaceres** [comment]
Seems to be working 💃

**Comment by saschanaz** [comment]
I hope we had an option to not see the new "Delete fork" button 😅

**Comment by marcoscaceres** [comment]
> I hope we had an option to not see the new "Delete fork" button 

Yeah, agree. I wasn't sure what you meant until I saw that button recently. I guess it makes sense, as 90% of the repos in my own account are ones I only did quick fixes for... but still a bit scary that you can potentially trash a legit fork so easily.

**Pull request merged**
